name: ml_pipline
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - jupyterlab=2.3.1
  - pydantic=1.9.0
  - numpy=1.20.3
  - pandas=1.4.2
  - python=3.8.10
  - matplotlib=3.5.1
  - requests=2.28.0
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - scipy=1.6.3
  - xgboost=1.5.0
  - catboost=0.26.1
  - pip:
    - beautifulsoup4==4.10.0
    - bs4==0.0.1
    - streamlit==1.0.0
    - uvicorn==0.18.2
    - fastapi==0.78.0